### Generated by Winemaker 0.8.4
###
### Invocation command line was
### /opt/local/bin/winemaker --lower-uppercase --mfc /Users/apple/RamseyX


SRCDIR                = .
SUBDIRS               =
DLLS                  =
LIBS                  =
EXES                  = ramseyx.exe



### Common settings

CEXTRA                = -mno-cygwin
CXXEXTRA              =
RCEXTRA               =
DEFINES               =
INCLUDE_PATH          = -I. \
			$(MFC_INCLUDE_PATH)
DLL_PATH              =
DLL_IMPORTS           =
LIBRARY_PATH          =
LIBRARIES             =


### ramseyx.exe sources and settings

ramseyx_exe_MODULE    = ramseyx.exe
ramseyx_exe_C_SRCS    = dhry_1.c \
			dhry_2.c
ramseyx_exe_CXX_SRCS  = CPUInfo.cpp \
			Graph.cpp \
			LoginDlg.cpp \
			MyCurlWrapper.cpp \
			RamseyX.cpp \
			RamseyXDlg.cpp \
			RamseyXTask.cpp \
			Set.cpp \
			SignupDlg.cpp \
			Splash.cpp
ramseyx_exe_RC_SRCS   = RamseyX.rc
ramseyx_exe_LDFLAGS   = -mwindows \
			-mno-cygwin
ramseyx_exe_ARFLAGS   =
ramseyx_exe_DLL_PATH  = $(MFC_LIBRARY_PATH)
ramseyx_exe_DLLS      = odbc32 \
			ole32 \
			oleaut32 \
			winspool \
			odbccp32 \
			mfc.dll
ramseyx_exe_LIBRARY_PATH= $(MFC_LIBRARY_PATH)
ramseyx_exe_LIBRARIES = uuid \
			mfc \
			winmm \
			libcurl_imp

ramseyx_exe_OBJS      = $(ramseyx_exe_C_SRCS:.c=.o) \
			$(ramseyx_exe_CXX_SRCS:.cpp=.o) \
			$(ramseyx_exe_RC_SRCS:.rc=.res)



### Global source lists

C_SRCS                = $(ramseyx_exe_C_SRCS)
CXX_SRCS              = $(ramseyx_exe_CXX_SRCS)
RC_SRCS               = $(ramseyx_exe_RC_SRCS)


### Tools

CC = winegcc
CXX = wineg++
RC = wrc
AR = ar


### Generic targets

all: $(SUBDIRS) $(DLLS:%=%.so) $(LIBS) $(EXES)

### Build rules

.PHONY: all clean dummy

$(SUBDIRS): dummy
	@cd $@ && $(MAKE)

# Implicit rules

.SUFFIXES: .cpp .cxx .rc .res
DEFINCL = $(INCLUDE_PATH) $(DEFINES) $(OPTIONS)

.c.o:
	$(CC) -c $(CFLAGS) $(CEXTRA) $(DEFINCL) -o $@ $<

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(CXXEXTRA) $(DEFINCL) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(CXXEXTRA) $(DEFINCL) -o $@ $<

.rc.res:
	$(RC) $(RCFLAGS) $(RCEXTRA) $(DEFINCL) -fo$@ $<

# Rules for cleaning

CLEAN_FILES     = y.tab.c y.tab.h lex.yy.c core *.orig *.rej \
                  \\\#*\\\# *~ *% .\\\#*

clean:: $(SUBDIRS:%=%/__clean__) $(EXTRASUBDIRS:%=%/__clean__)
	$(RM) $(CLEAN_FILES) $(RC_SRCS:.rc=.res) $(C_SRCS:.c=.o) $(CXX_SRCS:.cpp=.o)
	$(RM) $(DLLS:%=%.so) $(LIBS) $(EXES) $(EXES:%=%.so)

$(SUBDIRS:%=%/__clean__): dummy
	cd `dirname $@` && $(MAKE) clean

$(EXTRASUBDIRS:%=%/__clean__): dummy
	-cd `dirname $@` && $(RM) $(CLEAN_FILES)

### Target specific build rules
DEFLIB = $(LIBRARY_PATH) $(LIBRARIES) $(DLL_PATH) $(DLL_IMPORTS:%=-l%)

$(ramseyx_exe_MODULE): $(ramseyx_exe_OBJS)
	$(CXX) $(ramseyx_exe_LDFLAGS) -o $@ $(ramseyx_exe_OBJS) $(ramseyx_exe_LIBRARY_PATH) $(ramseyx_exe_DLL_PATH) $(DEFLIB) $(ramseyx_exe_DLLS:%=-l%) $(ramseyx_exe_LIBRARIES:%=-l%)


